###### Q: create 2D-array that contain even numbers between 0-18...??

In [4]:
import numpy as np

a=np.arange(0,18,2).reshape(3,3)
a

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

###### Q: Replace the negative values with 0 in random array that has value in range (-6,6)

In [13]:
x=np.random.randint(-6,6,25)
x

array([-3, -4,  5,  0, -2, -6,  4,  3, -3, -4,  4, -2, -1, -6,  0, -6,  3,
        5, -5,  5, -2, -3, -5,  1,  0])

In [14]:
x[x < 0] = 0

In [15]:
x

array([0, 0, 5, 0, 0, 0, 4, 3, 0, 0, 4, 0, 0, 0, 0, 0, 3, 5, 0, 5, 0, 0,
       0, 1, 0])

###### Q :  How to compute ((A+B)*(-A/2)) ?  where A,B random array

In [16]:
A=np.random.randint(1,10,(3,3))
A

array([[2, 8, 3],
       [1, 8, 8],
       [9, 6, 3]])

In [17]:
B=np.random.randint(10,100,(3,3))
B

array([[63, 14, 52],
       [96, 99, 51],
       [10, 56, 62]])

In [18]:
np.add(A,B) * (A * -1/2)

array([[ -65. ,  -88. ,  -82.5],
       [ -48.5, -428. , -236. ],
       [ -85.5, -186. ,  -97.5]])

#### Q: Scaling a 3x3 random matrix ??? 
(**hint**: (x - x_min) / x_max-x_min)

In [22]:
s=100*np.random.rand(3,3)
s

array([[15.72959614, 79.57915162, 79.52601018],
       [67.7848252 , 34.29086851, 31.23559496],
       [49.38604485, 29.14701993, 10.66852038]])

In [23]:
(s-np.min(s))/ (np.max(s)-np.min(s))

array([[0.07344405, 1.        , 0.99922884],
       [0.82884605, 0.34279686, 0.29846011],
       [0.56185125, 0.26815165, 0.        ]])

#### Q: Standerdize a 5x5 random matrix ??? 
(**hint**: (x - mean) / std)

In [20]:
r=10*np.random.rand(5,5)
r

array([[1.05157197, 2.56178489, 1.74533974, 6.10272855, 2.54445731],
       [1.15927502, 1.82309071, 5.59240046, 0.63596814, 9.05330571],
       [3.82211352, 4.76098049, 7.56534082, 1.50244887, 7.3499106 ],
       [7.68188006, 0.22173004, 5.38340357, 1.12204135, 8.59535351],
       [3.05663382, 5.30622881, 7.31829893, 7.49637093, 7.23392514]])

In [21]:
(r-np.mean(r)) / np.std(r)

array([[-1.20496366, -0.66592034, -0.95733574,  0.59795577, -0.6721051 ],
       [-1.16652099, -0.92958393,  0.41580335, -1.35330597,  1.65111119],
       [-0.21606872,  0.11904295,  1.1200089 , -1.04403126,  1.04311496],
       [ 1.16160549, -1.5011608 ,  0.34120567, -1.17981088,  1.48765339],
       [-0.48929292,  0.31365953,  1.03183174,  1.09539134,  1.00171604]])

###### Q: concatenate two arrays horizontally..?

In [39]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
np.concatenate([a, b], axis=1)


array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

#### Q: Create a random vector of size 3x3 and sort values in Its columns

In [43]:
a=np.random.randint(0,10,9).reshape(3,3)
a

array([[3, 9, 7],
       [2, 1, 9],
       [5, 9, 3]])

In [46]:
np.sort(a,axis=0)

array([[2, 1, 3],
       [3, 9, 7],
       [5, 9, 9]])